#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# IMPORTS
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

from src.thirdparty.misc import *;
from src.thirdparty.quantum import *;
from src.thirdparty.render import *;
from src.thirdparty.types import *;

from src.api import *;
from src.algorithms import *;

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# EXPORTS
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

__all__ = [
    'action_display_circuit',
    'action_display_statistics',
    'action_prepare_circuit_and_job',
];

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# METHODS - ACTIONS
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

def action_display_circuit():
    '''
    Displays the main part of the teleportation protocol.
    '''
    print('Quantumcircuit for Teleportation:');
    circuit = teleportation_protocol(include_entanglement=False);
    display(circuit.draw(output=DRAW_MODE.COLOUR.value, cregbundle=False, initial_state=False));
    return;

def action_prepare_circuit_and_job(
    option: BACKEND | BACKEND_SIMULATOR,
    num_shots: int,
    num_samples: int,
):
    '''
    Displays the entire quantum teleoportation protocol for test purposes:

    - initialisation of an entangle state between Alice and Bob
    - sampling of random states to teleport (via 'random' unitaries - in turn generated by random parameters)
    - the main teleportation circuit for the teleportation algorithm
    - the final part involves (Test-)Bob apply the inverses of the 'random' unitaries and measuring against |0⟩.

    @inputs
    - `backend` - an enum value to indicate which backend to use.
    - `num_shots` - number of shots of the job prepared for each random state.
    - `num_samples` - number of 'random' states to teleport
    '''
    @connect_to_backend(option=option, n=3)
    def action(
        option: BACKEND | BACKEND_SIMULATOR,
        backend: QkBackend,
        num_shots: int,
        num_samples: int,
    ):
        # create circuit:
        print('Quantumcircuit for testing teleportation protocol');
        circuit_scheme, params = teleportation_protocol_test();

        # display circuit:
        display(circuit_scheme.draw(
            output        = DRAW_MODE.COLOUR.value,
            cregbundle    = False,
            initial_state = True,
        ));

        # instantiate schema with random values and transpile:
        circuits = [
            circuit_scheme.bind_parameters({
                param_i: value_i
                for param_i, value_i in zip(params, values)
            })
            for values in random_unitary_parameters(n=num_samples)
        ];
        circuits = [ qk_transpile(circuit, backend) for circuit in circuits ];
        for circuit in circuits:
            circuit.name = circuit_scheme.name;

        # create job:
        # %qiskit_job_watcher
        job = qk_execute(
            experiments = circuits,
            backend = backend,
            shots = num_shots,
            optimization_level = 3,
        );
        print(latest_info(backend=backend, job=job));
        latest_state.set_job(job, queue=isinstance(option, BACKEND));
        return;

    action(num_shots=num_shots, num_samples=num_samples);
    return;

def action_display_statistics(queue: bool = False):
    '''
    Displays statistics of the job results of running the teleportation protocol.

    @inputs
    - `queue` - <boolean> `true` = display widget to choose job from IBM backend queue. `false` = use latest simulation.
    '''
    @recover_job(queue=queue, ensure_job_done=True, use_latest=True)
    def action(job: IBMQJob):
        result = job.result();
        _, [counts_alice, counts_bob] = get_counts(result, [0,1], [2]);
        display(QkVisualisation.plot_histogram(counts_alice, title='Measurements of Alice\'s QBits'));
        display(QkVisualisation.plot_histogram(counts_bob, title='Measurements of Bob\'s QBits'));

    action();
    return;
